"""Adiciona coluna email à tabela doador

Revision ID: 8f2b508c34e1
Revises: 
Create Date: 2024-08-08 16:31:17.822994

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f2b508c34e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doador')
    op.drop_table('doacao')
    op.drop_table('adotante')
    op.drop_table('animal')
    op.drop_table('voluntario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voluntario',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('contato', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('funcao', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('disponibilidade', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='voluntario_pkey')
    )
    op.create_table('animal',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('animal_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('especie', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('raca', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('idade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sexo', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('data_resgate', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('historico_medico', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='animal_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('adotante',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('contato', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('data_adocao', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('animal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], name='adotante_animal_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='adotante_pkey')
    )
    op.create_table('doacao',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('valor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('doador_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doador_id'], ['doador.id'], name='doacao_doador_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='doacao_pkey')
    )
    op.create_table('doador',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('contato', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('historico_doacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='doador_pkey')
    )
    # ### end Alembic commands ###
